### ISSUE TITLE
Submit Stalker PVR client addon upstream for mainstream inclusion?

### ISSUE THREAD

**Issue by Hedda** [kenji123/pvr.stalker#3]
Hi @kenji123  thanks for this great work! 

Awesome that you are working here on an open source Stalker middleware PVR client addon for Kodi!

I was just wondering if and when you plan on submit your Stalker PVR client addon upstream to kodi-pvr repository here on GitHub for mainstream inclusion?

I believe that it first need to be moved or forked to the kodi-pvr project on GitHub

https://github.com/kodi-pvr

It then needs to be submitted to as a pull request to xbmc/xbmc 

https://github.com/xbmc/xbmc/

Curious if you have an ETA on that and it it will make it upstream into mainstream before Kodi 15 ("Isengard") goes Beta or at least before final?

http://forum.kodi.tv/showthread.php?tid=219257

I think that this new PVR client addon will get a lot more attention from testers and other developers if it was included in upstream repo, even it is it only early test versions now.

**Comment by Hedda** [comment]
See xbmc/xbmc pull request 6985 as an example https://github.com/xbmc/xbmc/pull/6985

**Comment by kenji123** [comment]
It may be moving to kodi-pvr soon. Just sit tight.

**Comment by kenji123** [comment]
@Hedda 

https://github.com/kodi-pvr/pvr.stalker
https://github.com/xbmc/xbmc/pull/7036
